// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKF0RVPftH4GT-aYcjwi1__8DmgtIaNT8',
    appId: '1:667066161263:web:8679be96be0fda1c3d959a',
    messagingSenderId: '667066161263',
    projectId: 'voyra-app-a6f9d',
    authDomain: 'voyra-app-a6f9d.firebaseapp.com',
    storageBucket: 'voyra-app-a6f9d.firebasestorage.app',
    measurementId: 'G-07DJR5E3MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7tGXhtAsPN_A6JkozY10tt2MDiZxqb8',
    appId: '1:667066161263:android:436d1a990141ca153d959a',
    messagingSenderId: '667066161263',
    projectId: 'voyra-app-a6f9d',
    storageBucket: 'voyra-app-a6f9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrZMj2_cm7HMYE8zlDczPPZSHAgMMVkTM',
    appId: '1:667066161263:ios:b0aa5db2eb33de403d959a',
    messagingSenderId: '667066161263',
    projectId: 'voyra-app-a6f9d',
    storageBucket: 'voyra-app-a6f9d.firebasestorage.app',
    iosBundleId: 'com.example.voyraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrZMj2_cm7HMYE8zlDczPPZSHAgMMVkTM',
    appId: '1:667066161263:ios:b0aa5db2eb33de403d959a',
    messagingSenderId: '667066161263',
    projectId: 'voyra-app-a6f9d',
    storageBucket: 'voyra-app-a6f9d.firebasestorage.app',
    iosBundleId: 'com.example.voyraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKF0RVPftH4GT-aYcjwi1__8DmgtIaNT8',
    appId: '1:667066161263:web:b303bd361bb9cfde3d959a',
    messagingSenderId: '667066161263',
    projectId: 'voyra-app-a6f9d',
    authDomain: 'voyra-app-a6f9d.firebaseapp.com',
    storageBucket: 'voyra-app-a6f9d.firebasestorage.app',
    measurementId: 'G-G11PZ5L3EV',
  );
}
